[env]
LOG_LEVEL = "debug"

[tools]
"aqua:nodejs/node" = "24.11.1"
go = "1.23.4"
golangci-lint = "1.63.4"
dprint = "0.47.2"

[tasks.install]
run = "go mod download"

[tasks.codegen]
run = "go generate ./..."

[tasks.build]
run = "go build -o renovate-config ./cmd/lewtec-renovate-config"

[tasks.test]
run = "go test ./..."

[tasks."test:renovate"]
run = "npx -y renovate '--platform=local' '--repository-cache=reset'"

[tasks."lint:go"]
run = "golangci-lint run"

[tasks.lint]
depends = ["lint:*"]

[tasks."fmt:go"]
run = "go fmt ./..."

[tasks."fmt:dprint"]
run = "dprint fmt"

[tasks.fmt]
depends = ["fmt:*"]

[tasks.ci]
depends = ["lint", "test"]
