[env]
LOG_LEVEL = "debug"

[tools]
node = "24.19.0"
go = "1.23.4"
"go:golang.org/x/tools/gopls" = "0.21.0"

[tasks.build]
run = "go build -o renovate-config ./cmd/lewtec-renovate-config"

[tasks.test]
run = "go test ./..."

[tasks."test:renovate"]
run = "npx -y renovate '--platform=local' '--repository-cache=reset'"

[tasks.ci]
depends = ["test", "build"]
