package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/schollz/progressbar/v3"
	"github.com/spf13/cobra"
)

var (
	preset       string
	noPr         bool
	includeForks bool
)

const (
	defaultPreset = "github>lewtec/renovate-config:base"
	branchName    = "chore/add-renovate-config-preset"
	commitMessage = "chore: add renovate-config preset"
	prTitle       = "Add renovate-config preset"
	prBody        = `This PR adds the renovate-config preset to the repository's Renovate configuration.

The preset includes best practices and recommended configurations for dependency updates.

Changes:
- Added ` + "`extends`" + ` configuration to include ` + "`github>lewtec/renovate-config:base`" + `

This PR was automatically generated by the [renovate-config](https://github.com/lewtec/renovate-config) tool.`
)

var indentationRegex = regexp.MustCompile(`\n(\s+)`)

/**
 * Locates the Renovate configuration file within a repository.
 *
 * Checks standard locations (root, .github, .gitlab) and filenames
 * (renovate.json, .renovaterc.json, etc.) in order of precedence.
 * Returns the absolute path if found, or an empty string.
 */
func findRenovateConfig(repoPath string) string {
	possibleLocations := []string{
		"renovate.json",
		".github/renovate.json",
		".gitlab/renovate.json",
		".renovaterc.json",
		".renovaterc",
	}

	for _, loc := range possibleLocations {
		path := filepath.Join(repoPath, loc)
		if _, err := os.Stat(path); err == nil {
			slog.Info("Found renovate config", "path", path)
			return path
		}
	}
	return ""
}

/**
 * Heuristically detects the indentation style of a file.
 *
 * Scans for the first line break followed by whitespace to determine
 * if the file uses tabs or spaces (and how many). Defaults to 2 spaces
 * if no indentation pattern is found.
 */
func detectIndentation(content string) string {
	match := indentationRegex.FindStringSubmatch(content)
	if len(match) > 1 {
		indent := match[1]
		if strings.Contains(indent, "\t") {
			return "\t"
		}
		return indent
	}
	return "  "
}

/**
 * Updates the Renovate configuration to include the specified preset.
 *
 * This function performs the following operations:
 * 1. Reads and parses the existing JSON configuration.
 * 2. Normalizes the `extends` field (converting string to array if necessary).
 * 3. Checks if the preset is already present.
 *    - If present at the end: No change.
 *    - If present elsewhere: Moves it to the end to ensure it takes precedence.
 * 4. Appends the preset if missing.
 * 5. Writes the file back, attempting to preserve the original indentation.
 *
 * Returns true if the file was modified, false otherwise.
 */
func addPresetToConfig(configPath, presetRef string) (bool, error) {
	contentBytes, err := os.ReadFile(configPath)
	if err != nil {
		return false, err
	}
	content := string(contentBytes)

	indent := detectIndentation(content)

	var config map[string]interface{}
	if err := json.Unmarshal(contentBytes, &config); err != nil {
		slog.Error("Error parsing JSON", "error", err)
		return false, err
	}

	var extends []interface{}
	if val, ok := config["extends"]; ok {
		if list, ok := val.([]interface{}); ok {
			extends = list
		} else if str, ok := val.(string); ok {
			extends = []interface{}{str}
		}
	} else {
		extends = []interface{}{}
	}

	// Check if preset already exists
	foundIndex := -1
	for i, v := range extends {
		if s, ok := v.(string); ok && s == presetRef {
			foundIndex = i
			break
		}
	}

	if foundIndex != -1 {
		if foundIndex == len(extends)-1 {
			slog.Info("Preset already exists at the end of extends", "preset", presetRef)
			return false, nil
		}
		// Remove it to append at end
		extends = append(extends[:foundIndex], extends[foundIndex+1:]...)
		slog.Info("Moving preset to the end of extends array", "preset", presetRef)
	}

	extends = append(extends, presetRef)
	config["extends"] = extends

	// We need to marshal with indentation
	// Go's standard library doesn't easily support preserving exact indentation of the whole file if it's mixed,
	// but we will use the detected indent.
	// Use encoder to prevent HTML escaping (e.g., > becoming \u003e)
	var buf bytes.Buffer
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", indent)
	if err := encoder.Encode(config); err != nil {
		return false, err
	}

	outputBytes := buf.Bytes()

	if err := os.WriteFile(configPath, outputBytes, 0644); err != nil {
		return false, err
	}

	slog.Info("Added preset to extends array", "preset", presetRef)
	return true, nil
}


/**
 * Orchestrates the update process for a single repository.
 *
 * Workflow:
 * 1. Clones the repository to a temporary directory.
 * 2. Locates the Renovate config.
 * 3. Creates a new branch.
 * 4. Adds/Updates the preset in the config.
 * 5. Commits and pushes changes (if modified).
 * 6. Creates a PR (unless --no-pr is set or gh is unavailable).
 *
 * Returns 0 on success, 1 on failure.
 */
func processRepository(owner, repo, presetRef string, noPr bool, ghAvailable bool, ghError string) int {
	slog.Info("Processing repository", "repo", fmt.Sprintf("%s/%s", owner, repo))

	tmpDir, err := os.MkdirTemp("", "renovate-cli-*")
	if err != nil {
		slog.Error("Error creating temp dir", "error", err)
		return 1
	}
	defer os.RemoveAll(tmpDir)

	repoPath := filepath.Join(tmpDir, repo)

	slog.Info("Cloning repository", "repo", fmt.Sprintf("%s/%s", owner, repo))
	if !cloneRepository(owner, repo, repoPath) {
		return 1
	}

	configPath := findRenovateConfig(repoPath)
	if configPath == "" {
		slog.Error("No renovate configuration file found", "repo", fmt.Sprintf("%s/%s", owner, repo))
		return 1
	}

	defaultBranch := getDefaultBranch(repoPath)
	slog.Info("Default branch detected", "branch", defaultBranch)

	slog.Info("Creating branch", "branch", branchName)
	if _, err := runCommand(repoPath, "git", "checkout", "-b", branchName); err != nil {
		slog.Error("Error creating branch", "error", err)
		return 1
	}

	slog.Info("Updating renovate configuration")
	changesMade, err := addPresetToConfig(configPath, presetRef)
	if err != nil {
		slog.Error("Error updating config", "error", err)
		return 1
	}

	if !changesMade {
		slog.Info("No changes needed")
		return 0
	}

	slog.Info("Changes made")
	out, _ := runCommand(repoPath, "git", "diff", filepath.Base(configPath))
	if out != "" {
		slog.Debug("Git diff", "diff", out)
	}

	slog.Info("Committing changes")
	runCommand(repoPath, "git", "add", configPath)
	runCommand(repoPath, "git", "commit", "-m", commitMessage)

	// Delete remote branch if it exists to avoid conflicts
	slog.Info("Checking if remote branch exists")
	runCommand(repoPath, "git", "push", "origin", "--delete", branchName)

	slog.Info("Pushing branch", "branch", branchName)
	if output, err := runCommand(repoPath, "git", "push", "-u", "origin", branchName); err != nil {
		slog.Error("Error pushing branch", "error", err, "output", output)
		return 1
	}

	if !noPr {
		if ghAvailable {
			slog.Info("Creating pull request")
			createGitHubPR(repoPath, owner, repo, defaultBranch, branchName, prTitle, prBody)
		} else {
			slog.Warn("Cannot create PR", "reason", ghError)
			slog.Info("Branch pushed successfully", "branch", branchName)
		}
	} else {
		slog.Info("Branch pushed successfully", "branch", branchName)
	}

	slog.Info("Done with repository")
	return 0
}

func main() {
	handler := slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelInfo})
	slog.SetDefault(slog.New(handler))

	var rootCmd = &cobra.Command{
		Use:   "renovate-config [owner] [repo]",
		Short: "Add renovate-config preset to a GitHub repository",
		Args:  cobra.RangeArgs(1, 2),
		Run: func(cmd *cobra.Command, args []string) {
			owner := args[0]

			ghAvailable, ghError := checkGhCli()
			if !ghAvailable {
				slog.Warn("GitHub CLI warning", "warning", ghError)
				if !noPr {
					slog.Warn("PR creation will not be available. Use --no-pr to suppress this warning")
				}
			}

			if len(args) == 2 {
				repo := args[1]
				os.Exit(processRepository(owner, repo, preset, noPr, ghAvailable, ghError))
			} else {
				if !ghAvailable {
					slog.Error("GitHub CLI not available", "error", ghError)
					os.Exit(1)
				}
				repos, err := getRepositories(owner, includeForks)
				if err != nil {
					slog.Error("Error fetching repos", "error", err)
					os.Exit(1)
				}
				slog.Info("Found repositories", "count", len(repos), "repos", strings.Join(repos, ", "))

				bar := progressbar.Default(int64(len(repos)))

				failures := 0
				for _, repo := range repos {
					if res := processRepository(owner, repo, preset, noPr, ghAvailable, ghError); res != 0 {
						failures++
					}
					bar.Add(1)
				}
				if failures > 0 {
					slog.Error("Finished with failures", "failures", failures, "total", len(repos))
					os.Exit(1)
				}
				slog.Info("Successfully processed all repositories", "count", len(repos))
			}
		},
	}

	rootCmd.Flags().StringVar(&preset, "preset", defaultPreset, "Preset reference")
	rootCmd.Flags().BoolVar(&noPr, "no-pr", false, "Do not create a PR, just push the branch")
	rootCmd.Flags().BoolVar(&includeForks, "include-forks", false, "Include forked repositories when processing all repos")

	if err := rootCmd.Execute(); err != nil {
		slog.Error("Execution error", "error", err)
		os.Exit(1)
	}
}
