package main

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

const (
	branchName    = "chore/add-renovate-config-preset"
	commitMessage = "chore: add renovate-config preset"
	prTitle       = "Add renovate-config preset"
	prBody        = `This PR adds the renovate-config preset to the repository's Renovate configuration.

The preset includes best practices and recommended configurations for dependency updates.

Changes:
- Added ` + "`extends`" + ` configuration to include ` + "`github>lewtec/renovate-config:base`" + `

This PR was automatically generated by the [renovate-config](https://github.com/lewtec/renovate-config) tool.`
)

/**
 * Orchestrates the update process for a single repository.
 *
 * Workflow:
 * 1. Clones the repository to a temporary directory.
 * 2. Locates the Renovate config.
 * 3. Creates a new branch.
 * 4. Adds/Updates the preset in the config.
 * 5. Commits and pushes changes (if modified).
 * 6. Creates a PR (unless --no-pr is set or gh is unavailable).
 *
 * Returns 0 on success, 1 on failure.
 */
func processRepository(owner, repo, presetRef string, noPr bool, ghAvailable bool, ghError string) int {
	slog.Info("Processing repository", "repo", fmt.Sprintf("%s/%s", owner, repo))

	tmpDir, err := os.MkdirTemp("", "renovate-cli-*")
	if err != nil {
		ReportError(err, "Error creating temp dir")
		return 1
	}
	defer os.RemoveAll(tmpDir)

	repoPath := filepath.Join(tmpDir, repo)

	slog.Info("Cloning repository", "repo", fmt.Sprintf("%s/%s", owner, repo))
	if !cloneRepository(owner, repo, repoPath) {
		return 1
	}

	configPath := findRenovateConfig(repoPath)
	if configPath == "" {
		ReportError(fmt.Errorf("config not found"), "No renovate configuration file found", "repo", fmt.Sprintf("%s/%s", owner, repo))
		return 1
	}

	defaultBranch := getDefaultBranch(repoPath)
	slog.Info("Default branch detected", "branch", defaultBranch)

	slog.Info("Creating branch", "branch", branchName)
	if _, err := runCommand(repoPath, "git", "checkout", "-b", branchName); err != nil {
		ReportError(err, "Error creating branch")
		return 1
	}

	slog.Info("Updating renovate configuration")
	changesMade, err := addPresetToConfig(configPath, presetRef)
	if err != nil {
		ReportError(err, "Error updating config")
		return 1
	}

	if !changesMade {
		slog.Info("No changes needed")
		return 0
	}

	slog.Info("Changes made")
	out, err := runCommand(repoPath, "git", "diff", filepath.Base(configPath))
	if err != nil {
		ReportError(err, "Error running git diff")
	} else if out != "" {
		slog.Debug("Git diff", "diff", out)
	}

	slog.Info("Committing changes")
	if _, err := runCommand(repoPath, "git", "add", configPath); err != nil {
		ReportError(err, "Error adding changes")
		return 1
	}
	if _, err := runCommand(repoPath, "git", "commit", "-m", commitMessage); err != nil {
		ReportError(err, "Error committing changes")
		return 1
	}

	// Delete remote branch if it exists to avoid conflicts
	slog.Info("Checking if remote branch exists")
	if _, err := runCommand(repoPath, "git", "push", "origin", "--delete", branchName); err != nil {
		slog.Debug("Remote branch deletion failed (likely didn't exist)", "error", err)
	}

	slog.Info("Pushing branch", "branch", branchName)
	if output, err := runCommand(repoPath, "git", "push", "-u", "origin", branchName); err != nil {
		ReportError(err, "Error pushing branch", "output", output)
		return 1
	}

	if !noPr {
		if ghAvailable {
			slog.Info("Creating pull request")
			createGitHubPR(repoPath, owner, repo, defaultBranch, branchName, prTitle, prBody)
		} else {
			slog.Warn("Cannot create PR", "reason", ghError)
			slog.Info("Branch pushed successfully", "branch", branchName)
		}
	} else {
		slog.Info("Branch pushed successfully", "branch", branchName)
	}

	slog.Info("Done with repository")
	return 0
}
